Resume.Presentation/Areas/AdminPanel/Controllers/ContactMeController.cs
using Application.Service.Interface;
using Domain.Entities.ContactMe;
using Microsoft.AspNetCore.Mvc;

namespace Resume.Presentation.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    public class ContactMeController : Controller
    {
       
        #region ctor
        private readonly IContactMeService _contactMeService;
        public ContactMeController(IContactMeService contactMeService)
        {
            _contactMeService = contactMeService;
        }
        #endregion
        #region List Of ContactMe

        [HttpGet]
        public IActionResult ListOfAnContactMe()
        {
            var model = _contactMeService.GetListOFContactMe();

            return View(model);
        }
        #endregion
        #region Edit An ContactMe

        [HttpGet]
        public async Task<IActionResult> ChangeStatusOfSeenByAdmin(int educationId)
        {

            #region  Find An ContactMe By Id

            var education = await _contactMeService.FindContactMeByIdAsync(educationId);

            #endregion

            return View(education);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangeStatusOfSeenByAdmin(ContactMe contactMe)
        {
            #region Update An Education

            await _contactMeService.ChangeStatusOfSeenByAdmin(contactMe);

            return RedirectToAction(nameof(ListOfAnContactMe));

            #endregion

            return View(contactMe);
        }

        #endregion
    }
}

Resume.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">


<!--  from netgon.net/artstyles/v-card2/resume.html by /3.x , Fri, 10 Sep 2021 12:23:23 GMT -->
<head>
    <meta charset="utf-8" />
    <title>Pouria Vafaei</title>

	<script src="https://kit.fontawesome.com/16b7ed9380.js" crossorigin="anonymous"></script>

	<!-- Meta Data -->
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="format-detection" content="telephone=no"/>
    <meta name="format-detection" content="address=no"/>
    <meta name="author" content="ArtTemplate" />
    <meta name="description" content="P.Vafaei" />

    <!-- Twitter data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@@ArtTemplates">
    <meta name="twitter:title" content="vCard">
    <meta name="twitter:description" content="vCard">
    <meta name="twitter:image" content="/NewFolder2/assets/images/social.html">


    <!-- Open Graph data -->
    <meta property="og:title" content="ArtTemplate" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="your url website" />
    <meta property="og:image" content="/NewFolder2/assets/images/social.html" />
    <meta property="og:description" content="vCard" />
    <meta property="og:site_name" content="vCard" />

	<!-- Favicons -->
	<link rel="apple-touch-icon" sizes="144x144" href="/NewFolder2/assets/images/favicons/apple-touch-icon-144x144.png">
	<link rel="apple-touch-icon" sizes="114x114" href="/NewFolder2/assets/images/favicons/apple-touch-icon-114x114.png">
	<link rel="apple-touch-icon" sizes="72x72" href="/NewFolder2/assets/images/favicons/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="57x57" href="/NewFolder2/assets/images/favicons/apple-touch-icon-57x57.png">
	<link rel="shortcut icon" href="/NewFolder2/assets/img/avatar-6.jpg" type="image/png">

    <!-- Styles -->
	<link rel="stylesheet" type="text/css" href="/NewFolder2/assets/styles/style.css"/>
    <link rel="stylesheet" type="text/css" href="/NewFolder2/assets/demo/style-demo.css"/>
	
</head>
<body class="bg-triangles-2" style="background-color:black">
    <!-- Preloader -->
    <div class="preloader">
	    <div class="preloader__wrap">
			<svg class="spinner-container" viewBox="0 0 52 52">
                <circle class="path" cx="26px" cy="26px" r="20px" fill="none" stroke-width="4px" />
            </svg>
		    <div class="preloader__progress"><span></span></div>
		</div>
	</div>

    <main class="main">
	    <!-- Menu -->
		<div class="circle-menu">
			<div class="hamburger">
                <div class="line"></div>
                <div class="line"></div>
                <div class="line"></div>
				<div class="hamburger__text">MENU</div>
            </div>
		</div>
						
		<div class="nav-wrap">
			<ul class="nav">
                <li class="nav__item"><a class=" page-scroll" href="/About/index">About</a></li>
				<li class="nav__item"><a class=" page-scroll" href="/Home/index">Resume</a></li>
                <li class="nav__item"><a class=" page-scroll" href="/GitHub/index">GitHub</a></li>
                <li class="nav__item"><a class=" page-scroll" href="/Blog/index">Blog</a></li>
                <li class="nav__item"><a asp-action="index" asp-controller="ContactMe" asp-area="">ContactMe</a></li>
            </ul>
		</div>
		
	    <div class="wrapper">
			<!-- Sidebar -->
            <aside class="sidebar" data-simplebar>
			    <div>
			        <div class="avatar-wrap">
				        <svg class="avatar avatar--180" viewBox="0 0 188 188">
                            <g class="avatar__box">
                                <image xlink:href="/NewFolder2/assets/img/avatar-6.jpg" height="100%" width="100%" />
                            </g>
                        </svg>
				    </div>
				    <div class="text-center">
					    <h6 class="title sidebar__user-name"><span class="weight--500">Pouria</span> Vafaei</h6>
					    <div class="badge badge--gray" style="background-color:#f7972a">
							<a class="social__link" href="https://dotnet.microsoft.com/en-us/learn/dotnet/what-is-dotnet"><i class="fa-solid fa-laptop-code"></i></a>  .Net Developer</div>
							
					    <!-- Social -->
		                <div class="social">
		                    <a class="social__link" href="https://github.com/theOOwl"><i class="fa-brands fa-square-github fa-fade"></i></a>
		                    <a class="social__link" href="https://t.me/theOOwl"><i class="fa-brands fa-telegram fa-bounce"></i></a>
		                    <a class="social__link" href="https://www.linkedin.com/in/pouria-vafaeisabzevar-40523919a/"><i class="fa-brands fa-linkedin fa-fade"></i></a>
		                </div>
				    </div>

				    <ul class="contact-block">
					    <li class="contact-block__item" data-toggle="tooltip" data-placement="top" title="Birthday">
						    <i class="font-icon icon-calendar2"></i>Nov 16, 1998
					    </li>
					    <li class="contact-block__item" data-toggle="tooltip" data-placement="top" title="Address">
						    <i class="font-icon icon-map-pin"></i>Golestan,GBT, IRI
					    </li>
					    <li class="contact-block__item" data-toggle="tooltip" data-placement="top" title="E-mail">
						    <a style="font-size:x-small" href="mailto:example@mail.com"><i class="font-icon icon-mail"></i>pouriavafaei.code@gmail.com</a>
					    </li>
					    <li class="contact-block__item" data-toggle="tooltip" data-placement="top" title="Phone">
						    <i class="font-icon icon-smartphone"></i>+989114112986
					    </li>
					    <li class="contact-block__item" data-toggle="tooltip" data-placement="top" title="Skype">
						    <a href="skype:skype-Pouria Vafaei"><i class="font-icon icon-skype"></i>Pouria Vafaei</a>
					    </li>
				    </ul>
                </div>				
				<a class="btn" href="./NewFolder2/CV/CV.pdf" download="PouriaVafaei_CV"><i class="fa-solid fa-file-arrow-down fa-fade"></i>   Download CV</a>
		    </aside>
		        
			@RenderBody();
		   
		</div><!-- Wrapper End -->
    </main>

    <!-- SVG masks -->
    <svg class="svg-defs">
        <clipPath id="avatar-box">
            <path d="M1.85379 38.4859C2.9221 18.6653 18.6653 2.92275 38.4858 1.85453 56.0986.905299 77.2792 0 94 0c16.721 0 37.901.905299 55.514 1.85453 19.821 1.06822 35.564 16.81077 36.632 36.63137C187.095 56.0922 188 77.267 188 94c0 16.733-.905 37.908-1.854 55.514-1.068 19.821-16.811 35.563-36.632 36.631C131.901 187.095 110.721 188 94 188c-16.7208 0-37.9014-.905-55.5142-1.855-19.8205-1.068-35.5637-16.81-36.63201-36.631C.904831 131.908 0 110.733 0 94c0-16.733.904831-37.9078 1.85379-55.5141z"/>
        </clipPath>
        <clipPath id="avatar-hexagon">
             <path d="M0 27.2891c0-4.6662 2.4889-8.976 6.52491-11.2986L31.308 1.72845c3.98-2.290382 8.8697-2.305446 12.8637-.03963l25.234 14.31558C73.4807 18.3162 76 22.6478 76 27.3426V56.684c0 4.6805-2.5041 9.0013-6.5597 11.3186L44.4317 82.2915c-3.9869 2.278-8.8765 2.278-12.8634 0L6.55974 68.0026C2.50414 65.6853 0 61.3645 0 56.684V27.2891z"/>
        </clipPath>		
    </svg>

	<!-- Demo Menu -->
@*	<div class="btnSlideNav slideOpen"></div>
    <div class="btnSlideNav slideClose"></div>
    <ul class="slideNav">
	    <li class="slideNav__item rtl-mode"><h4 class="title title--5">More pages</h4> <a href="/NewFolder2/rtl/about.html">RTL</a></li>
		<li class="slideNav__item"><a href="one-page.html">1. Single page</a></li>
        <li class="slideNav__item"><a href="background-2.html">2. Background 2</a></li>
        <li class="slideNav__item"><a href="background-3.html">3. Background 3</a></li>
		<li class="slideNav__item"><a href="background-4.html">4. Background 4</a></li>
		<li class="slideNav__item"><a href="background-5.html">5. Background 5</a></li>
		<li class="slideNav__item"><a href="background-6.html">6. Background 6</a></li>
    </ul>
	<div class="overlay-slideNav"></div>*@
    <!-- Demo Menu -->

	<!-- JavaScripts -->
	<script src="/NewFolder2/assets/js/jquery-3.4.1.min.js"></script>
	<script src="/NewFolder2/assets/js/plugins.min.js"></script>
    <script src="/NewFolder2/assets/js/common.js"></script>
    
	<script src="/NewFolder2/assets/demo/plugins-demo.js"></script>
</body>

<!--  from netgon.net/artstyles/v-card2/resume.html by /3.x , Fri, 10 Sep 2021 12:23:23 GMT -->
</html>




	