Resume.Presentation/Areas/AdminPanel/Controllers/EducationController.cs
using Application.DTOs.AdminSide.Education;
using Application.Service.Interface;
using Domain.Models.Entities.Education;
using Microsoft.AspNetCore.Mvc;

namespace Resume.Presentation.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    public class EducationController : Controller
    {
        #region ctor
        private readonly IEducationService _educationService;
        public EducationController(IEducationService educationService)
        {
            _educationService = educationService;   
        }
        #endregion
        #region List Of Educations

        [HttpGet]
        public IActionResult ListOfAnEducations()
        {
            var model = _educationService.GetListOFEducations();

            return View(model);
        }

        #endregion
        #region Create An Education

        [HttpGet]
        public IActionResult CreateAnEducation()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAnEducation(CreateAnExperienceAdminSideDTO model)
        {
            if (ModelState.IsValid)
            {
                await _educationService.AddEducationToDataBase(model);

                return RedirectToAction(nameof(ListOfAnEducations));
            }

            return View();
        }

        #endregion
        #region Edit An Education

        [HttpGet]
        public async Task<IActionResult> EditAnEducation(int educationId)
        {
            #region Get An Education By Id

            var education = await _educationService.GetAnEducationByIdAsync(educationId);

            #endregion

            return View(education);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAnEducation(Education education)
        {
            #region Update An Education

            await _educationService.EditAnEducation(education);

            return RedirectToAction(nameof(ListOfAnEducations));

            #endregion

            return View(education);
        }

        #endregion
        #region Delete An Education

        [HttpGet]
        public async Task<IActionResult> DeleteAnEducation(int educationId)
        {
            #region Get An Education By Id

            var education = await _educationService.GetAnEducationByIdAsync(educationId);

            #endregion

            return View(education);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAnEducation(Education education)
        {
            #region Update An Education

            await _educationService.DeleteAnEducation(education);

            return RedirectToAction(nameof(ListOfAnEducations));

            #endregion

            return View(education);
        }
        #endregion
    }
}

Resume.Presentation/Areas/AdminPanel/Views/Education/CreateAnEducation.cshtml
@model Application.DTOs.AdminSide.Education.CreateAnExperienceAdminSideDTO
@{
    ViewData["Title"] = "CreateAnEducations Page";
    Layout = "_AdminLayout";

}

<div class="content-wrapper" style="min-height: 265.6px;">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">افزودن سابقه ی تحصیلی</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="/AdminPanel">داشبورد ادمین</a></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-success">
                        <div class="card-header">
                            <h3 class="card-title">ارسال اطلاعات سوابق تحصیلی</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form asp-action="CreateAnEducation" asp-area="AdminPanel" asp-controller="Education" method="post">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">عنوان مدرک تحصیلی</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="EducationTitle" placeholder="عنوان مدرک تحصیلی را وارد کنید">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">بازه ی زمانی دریافت مدرک</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="EducationDuration" placeholder="بازه ی زمانی دریافت مدرک را وارد کنید">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">توضیحات</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="Description" placeholder="توضیحات را وارد کنید">
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-success">ارسال</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

</div>

Resume.Presentation/Areas/AdminPanel/Views/Education/DeleteAnEducation.cshtml
@model Domain.Models.Entities.Education.Education
@{
    ViewData["Title"] = "DeleteAnEducations Page";
    Layout = "_AdminLayout";

}

<div class="content-wrapper" style="min-height: 265.6px;">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">حذف سابقه ی تحصیلی</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="/AdminPanel">داشبورد ادمین</a></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-danger">
                        <div class="card-header">
                            <h3 class="card-title">حذف اطلاعات سوابق تحصیلی</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form asp-action="DeleteAnEducation" asp-area="AdminPanel" asp-controller="Education" method="post">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Id</label>
                                    <input type="text" readonly class="form-control" id="exampleInputEmail1" asp-for="Id">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">عنوان مدرک تحصیلی</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="EducationTitle" placeholder="عنوان مدرک تحصیلی را وارد کنید">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">بازه ی زمانی دریافت مدرک</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="EducationDuration" placeholder="بازه ی زمانی دریافت مدرک را وارد کنید">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">توضیحات</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="Description" placeholder="توضیحات را وارد کنید">
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-danger">حذف</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

</div>

Resume.Presentation/Areas/AdminPanel/Views/Education/EditAnEducation.cshtml
@model Domain.Models.Entities.Education.Education
@{
    ViewData["Title"] = "EditAnEducations Page";
    Layout = "_AdminLayout";

}
<div class="content-wrapper" style="min-height: 265.6px;">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">ویرایش سابقه ی تحصیلی</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="/AdminPanel">داشبورد ادمین</a></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">ویرایش اطلاعات سوابق تحصیلی</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form asp-action="EditAnEducation" asp-area="AdminPanel" asp-controller="Education" method="post">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Id</label>
                                    <input type="text" readonly class="form-control" id="exampleInputEmail1" asp-for="Id" >
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">عنوان مدرک تحصیلی</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="EducationTitle" placeholder="عنوان مدرک تحصیلی را وارد کنید">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">بازه ی زمانی دریافت مدرک</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="EducationDuration" placeholder="بازه ی زمانی دریافت مدرک را وارد کنید">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">توضیحات</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="Description" placeholder="توضیحات را وارد کنید">
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">ارسال</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

</div>

Resume.Presentation/Areas/AdminPanel/Views/Education/ListOfAnEducations.cshtml
@model List<Domain.Models.Entities.Education.Education>
@{
    ViewData["Title"] = "ListOfAnEducations Page";
    Layout = "_AdminLayout";

}

<div class="content-wrapper" style="min-height: 265.6px;">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">لیست تحصیلات</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="/AdminPanel">داشبورد ادمین</a></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">

                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">جدول تحصیلات</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <table class="table table-striped">
                                <tbody>
                                    <tr>
                                        <th style="width: 10px">ردیف</th>
                                        <th>نام مدرک تحصیلی</th>
                                        <th>بازه ی زمانی </th>
                                        <th>توضیحات</th>
                                        <th>امکانات</th>
                                    </tr>

                                    @foreach (var education in Model)
                                    {
                                        <tr>
                                            <td>@education.Id</td>
                                            <td>@education.EducationTitle</td>
                                            <td>
                                                @education.EducationDuration
                                            </td>
                                            <td>
                                                @education.Description
                                            </td>
                                            <td>
                                                <a class="badge badge-primary" style="cursor:pointer;"
                                                   asp-action="EditAnEducation"
                                                   asp-area="AdminPanel"
                                                   asp-controller="Education"
                                                   asp-route-educationId="@education.Id">
                                                    ویرایش
                                               </a>

                                                <a class="badge badge-danger" style="cursor:pointer;"
                                                   asp-action="DeleteAnEducation"
                                                   asp-area="AdminPanel"
                                                   asp-controller="Education"
                                                   asp-route-educationId="@education.Id">حذف</a>
                                            </td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
</div>