Resume.Presentation/Areas/AdminPanel/Controllers/ExperienceController.cs
using Application.DTOs.AdminSide.Experience;
using Application.Service.Interface;
using Domain.Models.Entities.Experience;
using Microsoft.AspNetCore.Mvc;

namespace Resume.Presentation.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    public class ExperienceController : Controller
    {
        #region ctor
        private readonly IExperienceService _experienceService;
        public ExperienceController(IExperienceService ExperienceService)
        {
            _experienceService = ExperienceService;
        }
        #endregion
        #region List Of Experiences

        [HttpGet]
        public IActionResult ListOfAnExperience()
        {
            var model = _experienceService.GetListOfExperience();

            return View(model);
        }

        #endregion
        #region Create An Experience

        [HttpGet]
        public IActionResult CreateAnExperience()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAnExperience(CreateAnExperienceAdminSideDTO model)
        {
            if (ModelState.IsValid)
            {
                await _experienceService.AddExperienceToDataBase(model);

                return RedirectToAction(nameof(ListOfAnExperience));
            }

            return View();
        }

        #endregion
        #region Edit An Experience

        [HttpGet]
        public async Task<IActionResult> EditAnExperience(int experienceId)
        {
            #region Get An Experience By Id

            var experience = await _experienceService.GetAnExperienceByIdAsync(experienceId);

            #endregion

            return View(experience);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAnExperience(Experience experience)
        {
            #region Update An Experience

            await _experienceService.EditAnExperience(experience);

            return RedirectToAction(nameof(ListOfAnExperience));

            #endregion

            return View(experience);
        }

        #endregion
        #region Delete An Experience

        [HttpGet]
        public async Task<IActionResult> DeleteAnExperience(int experienceId)
        {
            #region Get An Experience By Id

            var experience = await _experienceService.GetAnExperienceByIdAsync(experienceId);

            #endregion

            return View(experience);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAnExperience(Experience experience)
        {
            #region Update An Experience

            await _experienceService.DeleteAnExperience(experience);

            return RedirectToAction(nameof(ListOfAnExperience));

            #endregion

            return View(experience);
        }
        #endregion
    }
}

Resume.Presentation/Areas/AdminPanel/Views/Experience/CreateAnExperience.cshtml
@model Application.DTOs.AdminSide.Experience.CreateAnExperienceAdminSideDTO
@{
    ViewData["Title"] = "CreateAnExperience Page";
    Layout = "_AdminLayout";

}

<div class="content-wrapper" style="min-height: 265.6px;">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">افزودن سابقه ی کاری</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="/AdminPanel">داشبورد ادمین</a></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-success">
                        <div class="card-header">
                            <h3 class="card-title">ارسال اطلاعات سوابق کاری</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form asp-action="CreateAnExperience" asp-area="AdminPanel" asp-controller="Experience" method="post">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">عنوان </label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="ExperienceTitle" placeholder="عنوان را وارد کنید">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">بازه ی زمانی مشغول به کار</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="ExperienceDuration" placeholder="بازه ی زمانی را وارد کنید">
                                </div>
                                 <div class="form-group">
                                    <label for="exampleInputEmail1">سایت شرکت</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="CompanySite" placeholder="سایت شرکت را وارد کنید">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">نام شرکت</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="CompanyName" placeholder="نام شرکت را وارد کنید">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">توضیحات</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="Description" placeholder="توضیحات را وارد کنید">
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-success">ارسال</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

</div>

Resume.Presentation/Areas/AdminPanel/Views/Experience/DeleteAnExperience.cshtml
@model Domain.Models.Entities.Experience.Experience
@{
    ViewData["Title"] = "DeleteAnExperiencePage";
    Layout = "_AdminLayout";

}

<div class="content-wrapper" style="min-height: 265.6px;">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">حذف سابقه ی شغلی</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="/AdminPanel">داشبورد ادمین</a></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-danger">
                        <div class="card-header">
                            <h3 class="card-title">حذف اطلاعات سوابق شغلی</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form asp-action="DeleteAnExperience" asp-area="AdminPanel" asp-controller="Experience" method="post">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Id</label>
                                    <input type="text" readonly class="form-control" id="exampleInputEmail1" asp-for="Id">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">عنوان شغلی</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="ExperienceTitle" placeholder="عنوان را وارد کنید">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">بازه ی زمانی </label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="ExperienceDuration" placeholder="بازه ی زمانی را وارد کنید">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">سایت شرکت</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="CompanySite" placeholder="سایت شرکت را وارد کنید">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">نام شرکت</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="CompanyName" placeholder="نام شرکت را وارد کنید">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">توضیحات</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="Description" placeholder="توضیحات را وارد کنید">
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-danger">حذف</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

</div>

Resume.Presentation/Areas/AdminPanel/Views/Experience/EditAnExperience.cshtml
@model Domain.Models.Entities.Experience.Experience
@{
    ViewData["Title"] = "EditAnExperience Page";
    Layout = "_AdminLayout";

}
<div class="content-wrapper" style="min-height: 265.6px;">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">ویرایش سابقه ی شغلی</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="/AdminPanel">داشبورد ادمین</a></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">ویرایش اطلاعات سوابق شغلی</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form asp-action="EditAnExperience" asp-area="AdminPanel" asp-controller="Experience" method="post">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Id</label>
                                    <input type="text" readonly class="form-control" id="exampleInputEmail1" asp-for="Id" >
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">عنوان سابقع شغلی</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="ExperienceTitle" placeholder="عنوان را وارد کنید">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">بازه ی زمانی  </label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="ExperienceDuration" placeholder="بازه ی زمانی  را وارد کنید">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1"> سایت شرکت </label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="CompanySite" placeholder="سایت شرکت را وارد کنید">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1"> نام شرکت </label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="CompanyName" placeholder="نام شرکت را وارد کنید">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">توضیحات</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="Description" placeholder="توضیحات را وارد کنید">
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">ارسال</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

</div>

Resume.Presentation/Areas/AdminPanel/Views/Experience/ListOfAnExperience.cshtml
@model List<Domain.Models.Entities.Experience.Experience>
@{
    ViewData["Title"] = "ListOfAnExperience Page";
    Layout = "_AdminLayout";

}

<div class="content-wrapper" style="min-height: 265.6px;">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">لیست سابقه شغلی</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="/AdminPanel">داشبورد ادمین</a></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">

                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">جدول سابقه شغلی</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <table class="table table-striped">
                                <tbody>
                                    <tr>
                                        <th style="width: 10px">ردیف</th>
                                        <th>عنوان شغلی</th>
                                        <th>بازه ی زمانی </th>
                                        <th>سایت شرکت</th>
                                        <th>نام شرکت</th>
                                        <th>توضیحات</th>
                                    </tr>

                                    @foreach (var experience in Model)
                                    {
                                        <tr>
                                            <td>@experience.Id</td>
                                            <td>@experience.ExperienceTitle</td>
                                            <td>
                                                @experience.ExperienceDuration
                                            </td>
                                            <td>
                                                @experience.CompanySite
                                            </td>
                                            <td>
                                                @experience.CompanyName
                                            </td>
                                            <td>
                                                @experience.Description
                                            </td>
                                            <td>
                                                <a class="badge badge-primary" style="cursor:pointer;"
                                                   asp-action="EditAnExperience"
                                                   asp-area="AdminPanel"
                                                   asp-controller="Experience"
                                                   asp-route-ExperienceId="@experience.Id">
                                                    ویرایش
                                               </a>

                                                <a class="badge badge-danger" style="cursor:pointer;"
                                                   asp-action="DeleteAnExperience"
                                                   asp-area="AdminPanel"
                                                   asp-controller="Experience"
                                                   asp-route-ExperienceId="@experience.Id">حذف</a>
                                            </td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
</div>