Resume.Presentation/Areas/AdminPanel/Controllers/MySkillsController.cs
using Application.DTOs.AdminSide.MySkills;
using Application.Service.Interface;
using Domain.Models.Entities.MySkills;
using Microsoft.AspNetCore.Mvc;

namespace Resume.Presentation.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    public class MySkillsController : Controller
    {
        #region ctor
        private readonly IMySkillsService _MySkillsService;
        public MySkillsController(IMySkillsService MySkillsService)
        {
            _MySkillsService = MySkillsService;
        }
        #endregion
        #region List Of MySkillss

        [HttpGet]
        public IActionResult ListOfAnMySkills()
        {
            var model = _MySkillsService.GetListOfMySkills();

            return View(model);
        }

        #endregion
        #region Create An MySkills

        [HttpGet]
        public IActionResult CreateAnMySkills()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAnMySkills(CreateAnMySkillsAdminSideDTO model)
        {
            if (ModelState.IsValid)
            {
                await _MySkillsService.AddMySkillsToDataBase(model);

                return RedirectToAction(nameof(ListOfAnMySkills));
            }

            return View();
        }

        #endregion
        #region Edit An MySkills

        [HttpGet]
        public async Task<IActionResult> EditAnMySkills(int MySkillsId)
        {
            #region Get An MySkills By Id

            var MySkills = await _MySkillsService.GetAnMySkillsByIdAsync(MySkillsId);

            #endregion

            return View(MySkills);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAnMySkills(MySkills MySkills)
        {
            #region Update An MySkills

            await _MySkillsService.EditAnMySkills(MySkills);

            return RedirectToAction(nameof(ListOfAnMySkills));

            #endregion

            return View(MySkills);
        }

        #endregion
        #region Delete An MySkills

        [HttpGet]
        public async Task<IActionResult> DeleteAnMySkills(int MySkillsId)
        {
            #region Get An MySkills By Id

            var MySkills = await _MySkillsService.GetAnMySkillsByIdAsync(MySkillsId);

            #endregion

            return View(MySkills);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAnMySkills(MySkills MySkills)
        {
            #region Update An MySkills

            await _MySkillsService.DeleteAnMySkills(MySkills);

            return RedirectToAction(nameof(ListOfAnMySkills));

            #endregion

            return View(MySkills);
        }
        #endregion
    }
}

Resume.Presentation/Areas/AdminPanel/Views/MySkills/CreateAnMySkills.cshtml
@model Application.DTOs.AdminSide.MySkills.CreateAnMySkillsAdminSideDTO
@{
    ViewData["Title"] = "CreateAnMySkills Page";
    Layout = "_AdminLayout";

}

<div class="content-wrapper" style="min-height: 265.6px;">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">افزودن مهارت</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="/AdminPanel">داشبورد ادمین</a></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-success">
                        <div class="card-header">
                            <h3 class="card-title">ارسال اطلاعات سوابق مهارت</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form asp-action="CreateAnMySkills" asp-area="AdminPanel" asp-controller="MySkills" method="post">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">عنوان </label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="SkillTille" placeholder="عنوان را وارد کنید">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">درصد تسلط</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="Percentage" placeholder="مقدار تسلط را وارد کنید">
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-success">ارسال</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

</div>

Resume.Presentation/Areas/AdminPanel/Views/MySkills/DeleteAnMySkills.cshtml
@model Domain.Models.Entities.MySkills.MySkills
@{
    ViewData["Title"] = "DeleteAnMySkillsPage";
    Layout = "_AdminLayout";

}

<div class="content-wrapper" style="min-height: 265.6px;">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">حذف مهارت</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="/AdminPanel">داشبورد ادمین</a></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-danger">
                        <div class="card-header">
                            <h3 class="card-title">حذف مهارت</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form asp-action="DeleteAnMySkills" asp-area="AdminPanel" asp-controller="MySkills" method="post">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Id</label>
                                    <input type="text" readonly class="form-control" id="exampleInputEmail1" asp-for="Id">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">عنوان</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="SkillTille" placeholder="عنوان را وارد کنید">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">درصد مهارت</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="Percentage" placeholder="مقدار تسلط را وارد کنید">
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-danger">حذف</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

</div>

Resume.Presentation/Areas/AdminPanel/Views/MySkills/EditAnMySkills.cshtml
@model Domain.Models.Entities.MySkills.MySkills
@{
    ViewData["Title"] = "EditAnMySkills Page";
    Layout = "_AdminLayout";

}
<div class="content-wrapper" style="min-height: 265.6px;">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">ویرایش مهارت</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="/AdminPanel">داشبورد ادمین</a></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">ویرایش مهارت</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form asp-action="EditAnMySkills" asp-area="AdminPanel" asp-controller="MySkills" method="post">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Id</label>
                                    <input type="text" readonly class="form-control" id="exampleInputEmail1" asp-for="Id" >
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">عنوان</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="SkillTille" placeholder="عنوان را وارد کنید">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">درصد تسلط</label>
                                    <input type="text" class="form-control" id="exampleInputEmail1" asp-for="Percentage" placeholder="مقدار تسلط را وارد کنید">
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">ارسال</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

</div>

Resume.Presentation/Areas/AdminPanel/Views/MySkills/ListOfAnMySkills.cshtml
@model List<Domain.Models.Entities.MySkills.MySkills>
@{
    ViewData["Title"] = "ListOfAnMySkills Page";
    Layout = "_AdminLayout";

}

<div class="content-wrapper" style="min-height: 265.6px;">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">لیست مهارت ها</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="/AdminPanel">داشبورد ادمین</a></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">

                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">جدول مهارت ها</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <table class="table table-striped">
                                <tbody>
                                    <tr>
                                        <th style="width: 10px">ردیف</th>
                                        <th>عنوان</th>
                                        <th>درصد تسلط </th>
                                    </tr>

                                    @foreach (var MySkills in Model)
                                    {
                                        <tr>
                                            <td>@MySkills.Id</td>
                                            <td>@MySkills.SkillTille</td>
                                            <td>
                                                @MySkills.Percentage
                                            </td>
                                            <td>
                                                <a class="badge badge-primary" style="cursor:pointer;"
                                                   asp-action="EditAnMySkills"
                                                   asp-area="AdminPanel"
                                                   asp-controller="MySkills"
                                                   asp-route-MySkillsId="@MySkills.Id">
                                                    ویرایش
                                               </a>

                                                <a class="badge badge-danger" style="cursor:pointer;"
                                                   asp-action="DeleteAnMySkills"
                                                   asp-area="AdminPanel"
                                                   asp-controller="MySkills"
                                                   asp-route-MySkillsId="@MySkills.Id">حذف</a>
                                            </td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
</div>